@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

package "BaseNoStates" {
    class Webserver {

    }

    class SocketThread {

    }

    class Clock extends Observable {

    }

    class Main {

    }
}


Main -[hidden]down- Webserver

package "UserGroups" {

    class DirectoryUserGroups {

    }

    class UserGroup {
         }

    class User {

    }

}

DirectoryUserGroups  -->  UserGroup : userGroups
UserGroup  -->  User : users

package "Partitions" {

    abstract class Area {
        }

    class Space {

    }

    class Partition {
    }

    class DirectoryAreas {
        }
}

Area "1" <-- DirectoryAreas : "rootArea"
Area <|-- Partition
Area <|-- Space
Area <|-- Door
Partition *--> "1" Area : "children"
Door  <--  Space : doors
Door  <--  DirectoryAreas : doors

package requests {
    interface Request {
    }

    class RequestRefresh implements Request {
    }

    class RequestReader implements Request {
     }

    class RequestArea implements Request {
    }
}

class Door {
}

package "DoorStates" {
    abstract class DoorState {
    }

    class States {

    }

    class Actions {

    }

    class Unlocked {

    }

    class Locked {

    }

    class UnlockedShortly {
    }


}
DoorState <|-- Unlocked
DoorState <|-- UnlockedShortly
DoorState <|-- Locked

DoorState <-- Door : state

SocketThread --> Request
Webserver --> SocketThread
SocketThread --> Request
SocketThread --> RequestReader
SocketThread --> RequestArea
RequestReader --> User
RequestReader --> UserGroup
RequestArea --> Area

@enduml